spring.application.name=report-service

server.port=8083
server.servlet.context-path=/api

spring.profiles.active=dev

management.otlp.metrics.export.enabled=false

shared.security.excluded-paths=/**/ping,/**/actuator/health,/**/actuator/info