spring.application.name=profile-service

server.port=8082
server.servlet.context-path=/api

spring.profiles.active=dev

management.otlp.metrics.export.enabled=false

shared.security.excluded-paths=/**/ping,/**/actuator/health,/**/actuator/info
