logging.file.path=/mnt/STORAGE/projects/work/researchportal-parent/logs/

service.routes.reports-service=http://localhost:8081/reports

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.default-zone=http://localhost:8761/eureka
eureka.client.registry-fetch-interval-seconds=20
eureka.instance.prefer-ip-address=true

#resilience4j.circuitbreaker.instances.reportService.slidingWindowSize=10
#resilience4j.circuitbreaker.instances.reportService.failureRateThreshold=2
#resilience4j.circuitbreaker.instances.reportService.waitDurationInOpenState=5s

resilience4j.circuitbreaker.instances.orderService.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.orderService.slidingWindowSize=2
resilience4j.circuitbreaker.instances.orderService.minimumNumberOfCalls=2
resilience4j.circuitbreaker.instances.orderService.failureRateThreshold=100
resilience4j.circuitbreaker.instances.orderService.waitDurationInOpenState=5s