logging.file.path=/mnt/STORAGE/projects/work/researchportal-parent/logs/

service.routes.reports-service=http://localhost:8081/reports

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.default-zone=http://localhost:8761/eureka
eureka.client.registry-fetch-interval-seconds=20
eureka.instance.prefer-ip-address=true